version: "3.7"

services:
  app:
    build:
      context: ./backend/.
    env_file:
      - ./backend/.env
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./backend:/app
    command: >
      sh -c  "npm run prisma:migrate:init && npm run start:dev"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: tech_test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./client:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
